#!/usr/bin/env bun
/**
 * Regenerate scaffold.canvas.tsx from app/src/Map.tsx.
 *
 *   bun scripts/build-canvas-scaffold.ts
 *   bun scripts/build-canvas-scaffold.ts --check
 */
import { resolve } from "node:path";

const skillRoot = resolve(import.meta.dir, "..");
const sourcePath = resolve(skillRoot, "app/src/Map.tsx");
const outPath = resolve(skillRoot, "scaffold.canvas.tsx");

const HEADER = `/**
 * Map scaffold — GENERATED by scripts/build-canvas-scaffold.ts
 * Do not edit by hand; edit app/src/Map.tsx then run:
 *   bun scripts/build-canvas-scaffold.ts
 * Copy to ~/.cursor/projects/<proj>/canvases/<name>.canvas.tsx
 * then: set ROOT, fill FILE_MAP / NODES / EDGES / ARCH_DIAGRAMS, run
 *   bun "$SKILL_DIR/scripts/update.ts" --file <this-file>
 */
`;

function usage(code = 2): never {
  console.error(`Usage:
  bun build-canvas-scaffold.ts [--check]

Reads app/src/Map.tsx and writes scaffold.canvas.tsx
(replacing ./host import with cursor/canvas).`);
  process.exit(code);
}

function generate(source: string): string {
  let body = source.replace(/^\/\*\*[\s\S]*?\*\/\s*/, "");
  body = body.replace(
    /from\s+["']\.\/host["']/,
    'from "cursor/canvas"',
  );
  if (!body.includes('from "cursor/canvas"')) {
    throw new Error(
      'Expected import from "./host" in Map.tsx (not found after transform)',
    );
  }
  return HEADER + body.replace(/^\n+/, "");
}

const check = Bun.argv.includes("--check");
if (Bun.argv.some((a) => a === "-h" || a === "--help")) usage(0);

const source = await Bun.file(sourcePath).text();
const generated = generate(source);

if (check) {
  const current = await Bun.file(outPath).text().catch(() => "");
  if (current !== generated) {
    console.error(
      "scaffold.canvas.tsx is out of date. Run: bun scripts/build-canvas-scaffold.ts",
    );
    process.exit(1);
  }
  console.log("scaffold.canvas.tsx is up to date");
  process.exit(0);
}

await Bun.write(outPath, generated);
console.log(`Wrote ${outPath}`);
