#!/usr/bin/env bun
/**
 * Map skill single update (Bun).
 *
 * Source of truth: `// <map:file-map> …` only.
 * Regenerates:
 *   1. FILE_CONTENTS  — full file bodies for preview popups
 *   2. MAP_PATHS      — unique abs paths for the right-hand file tree
 *
 * Usage (prefer `update`):
 *   bun update.ts --file /abs/map.canvas.tsx
 *   bun sync-file-map.ts --file /abs/map.canvas.tsx
 *   bun update.ts --canvas /abs/map.canvas.tsx
 *   bun update.ts --file map.canvas.tsx --check
 *   bun update.ts --file map.canvas.tsx --dry-run
 *   bun update.ts --file map.canvas.tsx --root /override/repo
 */
import { resolve, join, relative } from "node:path";

const BEGIN_MAP = "// <map:file-map>";
const END_MAP = "// </map:file-map>";
const BEGIN_CONTENTS = "// <map:file-contents>";
const END_CONTENTS = "// </map:file-contents>";
const BEGIN_PATHS = "// <map:map-paths>";
const END_PATHS = "// </map:map-paths>";
type Opts = {
  canvas: string;
  root: string | null;
  check: boolean;
  dryRun: boolean;
};

function usage(code = 2): never {
  console.error(`Usage:
  bun update.ts --file <map.canvas.tsx> [--root <abs>] [--check] [--dry-run]
  bun update.ts --canvas <map.canvas.tsx>   # alias for --file

Reads FILE_MAP only; rewrites FILE_CONTENTS + MAP_PATHS (file tree).
Does not search NODES/EDGES — add every code link to FILE_MAP.`);
  process.exit(code);
}

function parseArgs(argv: string[]): Opts {
  const out: Opts = { canvas: "", root: null, check: false, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--file" || a === "--canvas") {
      const next = argv[++i];
      if (!next) usage();
      out.canvas = next;
    } else if (a === "--root") {
      const next = argv[++i];
      if (!next) usage();
      out.root = next;
    } else if (a === "--check") out.check = true;
    else if (a === "--dry-run") out.dryRun = true;
    else if (a === "-h" || a === "--help") usage(0);
    else {
      console.error(`Unknown arg: ${a}`);
      usage();
    }
  }
  if (!out.canvas) usage();
  return out;
}

function escTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function sliceMarked(src: string, begin: string, end: string): string | null {
  const i = src.indexOf(begin);
  const j = src.indexOf(end);
  if (i < 0 || j < 0 || j < i) return null;
  return src.slice(i + begin.length, j);
}

function extractRoot(src: string, override: string | null): string {
  if (override) return resolve(override);
  const m = src.match(/const\s+ROOT\s*=\s*"([^"]+)"\s*;/);
  if (!m) throw new Error('Missing `const ROOT = "…";` (pass --root)');
  return resolve(m[1]!);
}

/** Strip // line comments so example paths in comments are not collected. */
function stripLineComments(s: string): string {
  return s.replace(/^\s*\/\/.*$/gm, "");
}

/** Paths from FILE_MAP only — `\`${ROOT}/rel\`` and absolute under root. */
function pathsFromFileMap(mapBody: string, root: string): string[] {
  const body = stripLineComments(mapBody);
  const abs = new Set<string>();
  for (const m of body.matchAll(/path:\s*`\$\{ROOT\}\/([^`]+)`/g)) {
    abs.add(join(root, m[1]!));
  }
  const rootEsc = root.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const absRe = new RegExp(`path:\\s*"(${rootEsc}/[^"]+)"`, "g");
  for (const m of body.matchAll(absRe)) {
    abs.add(resolve(m[1]!));
  }
  for (const m of body.matchAll(/path:\s*"([^"${][^"]+)"/g)) {
    const p = m[1]!;
    if (p.startsWith("/")) continue;
    abs.add(join(root, p));
  }
  return [...abs].sort((a, b) => a.localeCompare(b));
}

async function readUtf8(abs: string): Promise<string> {
  const f = Bun.file(abs);
  if (!(await f.exists())) throw new Error(`Missing on disk: ${abs}`);
  return f.text();
}

function buildContentsBlock(paths: string[], fileText: Map<string, string>): string {
  const entries = paths.map((abs) => {
    return `  [\`${abs}\`]: \`${escTemplate(fileText.get(abs)!)}\``;
  });
  return [
    BEGIN_CONTENTS,
    "/** Full file bodies for preview popups. Generated — do not edit. */",
    "/** @generated by scripts/sync-file-map.ts (bun update.ts) */",
    "const FILE_CONTENTS: Record<string, string> = {",
    entries.join(",\n"),
    "};",
    END_CONTENTS,
    "",
  ].join("\n");
}

function buildPathsBlock(paths: string[]): string {
  const entries = paths.map((abs) => `  \`${abs}\``);
  return [
    BEGIN_PATHS,
    "/** Unique abs paths for the file tree. Generated — do not edit. */",
    "/** @generated by scripts/sync-file-map.ts (bun update.ts) */",
    "const MAP_PATHS: string[] = [",
    entries.join(",\n"),
    "];",
    END_PATHS,
    "",
  ].join("\n");
}

function replaceMarked(
  src: string,
  begin: string,
  end: string,
  block: string,
): string | null {
  const i = src.indexOf(begin);
  const j = src.indexOf(end);
  if (i >= 0 && j > i) {
    return src.slice(0, i) + block + src.slice(j + end.length).replace(/^\n/, "");
  }
  return null;
}

function upsertMarked(
  src: string,
  begin: string,
  end: string,
  block: string,
  afterEnd: string,
): string {
  const replaced = replaceMarked(src, begin, end, block);
  if (replaced != null) return replaced;
  const anchor = src.indexOf(afterEnd);
  if (anchor < 0) {
    throw new Error(`Cannot insert ${begin} (missing ${afterEnd})`);
  }
  const at = anchor + afterEnd.length;
  return src.slice(0, at) + "\n\n" + block + src.slice(at).replace(/^\n*/, "\n");
}

function validateRanges(
  mapBody: string,
  root: string,
  fileText: Map<string, string>,
) {
  for (const m of mapBody.matchAll(
    /path:\s*`\$\{ROOT\}\/([^`]+)`\s*,\s*\n?\s*line:\s*(\d+)(?:\s*,\s*\n?\s*endLine:\s*(\d+))?/g,
  )) {
    const rel = m[1]!;
    const start = Number(m[2]);
    const end = m[3] != null ? Number(m[3]) : start;
    const abs = join(root, rel);
    const body = fileText.get(abs);
    if (!body) {
      console.warn(`warn: no body for ${rel}`);
      continue;
    }
    const n = body.replace(/\n$/, "").split("\n").length;
    if (start < 1 || end < start || end > n) {
      console.warn(`warn: ${rel}:${start}-${end} out of 1..${n}`);
    }
  }
}

async function main() {
  const opts = parseArgs(Bun.argv.slice(2));
  const canvasPath = resolve(opts.canvas);
  const canvasFile = Bun.file(canvasPath);
  if (!(await canvasFile.exists())) {
    console.error(`Canvas not found: ${canvasPath}`);
    process.exit(1);
  }

  const src = await canvasFile.text();
  const root = extractRoot(src, opts.root);
  const mapBody = sliceMarked(src, BEGIN_MAP, END_MAP);
  if (mapBody == null) {
    console.error(
      `Missing ${BEGIN_MAP} … ${END_MAP} block.\n` +
        "FILE_MAP is required — see code-preview.md. Do not scatter FileRefs in NODES.",
    );
    process.exit(1);
  }

  const paths = pathsFromFileMap(mapBody, root);
  if (paths.length === 0) {
    console.error("FILE_MAP has no path entries");
    process.exit(1);
  }

  console.error(`root: ${root}`);
  console.error(`FILE_MAP → ${paths.length} file(s)`);
  for (const p of paths) console.error(`  - ${relative(root, p)}`);

  const bodies = await Promise.all(
    paths.map(async (p) => [p, await readUtf8(p)] as const),
  );
  const fileText = new Map(bodies);
  validateRanges(mapBody, root, fileText);

  const contentsBlock = buildContentsBlock(paths, fileText);
  const pathsBlock = buildPathsBlock(paths);

  let next = upsertMarked(
    src,
    BEGIN_CONTENTS,
    END_CONTENTS,
    contentsBlock,
    END_MAP,
  );
  next = upsertMarked(
    next,
    BEGIN_PATHS,
    END_PATHS,
    pathsBlock,
    END_CONTENTS,
  );
  const changed = next !== src;

  if (opts.dryRun) {
    console.error(
      changed
        ? `dry-run: would rewrite FILE_CONTENTS + MAP_PATHS (${paths.length} files)`
        : "dry-run: already up to date",
    );
    process.exit(0);
  }

  if (opts.check) {
    if (changed) {
      console.error("check failed: run:");
      console.error(`  bun update.ts --file ${canvasPath}`);
      process.exit(1);
    }
    console.error("check ok");
    process.exit(0);
  }

  if (!changed) {
    console.error("already up to date");
    process.exit(0);
  }

  await Bun.write(canvasPath, next);
  console.error(`wrote ${canvasPath}`);
  console.error(`updated FILE_CONTENTS + MAP_PATHS (${paths.length} files)`);
}

await main();
