/**
 * Map scaffold — GENERATED by scripts/build-canvas-scaffold.ts
 * Do not edit by hand; edit app/src/Map.tsx then run:
 *   bun scripts/build-canvas-scaffold.ts
 * Copy to ~/.cursor/projects/<proj>/canvases/<name>.canvas.tsx
 * then: set ROOT, fill FILE_MAP / NODES / EDGES / ARCH_DIAGRAMS, run
 *   bun "$SKILL_DIR/scripts/update.ts" --file <this-file>
 */
import {
  Button,
  Code,
  DiffView,
  H1,
  IconButton,
  Pill,
  Row,
  Stack,
  Text,
  useCanvasAction,
  useCanvasState,
  useHostTheme,
  type DiffLineData,
} from "cursor/canvas";
import * as MapHost from "cursor/canvas";
import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";

type FileRef = {
  path: string;
  line?: number;
  /** Inclusive end of highlight range; defaults to `line` when omitted. */
  endLine?: number;
  label?: string;
};

type DocBlock =
  | { type: "prose"; text: string }
  /** `ref` must be a key of `FILE_MAP` (single source of truth below). */
  | { type: "code"; ref: string; caption?: string };

type MapNode = {
  id: string;
  label: string;
  teaser: string;
  body: DocBlock[];
  files: FileRef[];
};

type MapEdge = {
  from: string;
  to: string;
  label: string;
  body: DocBlock[];
  files: FileRef[];
};

type View = { x: number; y: number; zoom: number };

type Focus =
  | { kind: "node"; id: string }
  | { kind: "edge"; key: string };

type ArchHotspot = { label: string; nodeId?: string; edgeKey?: string };
type ArchDiagram = {
  id: string;
  title: string;
  kind: "flowchart" | "sequence" | "class" | "er" | "state";
  svg: string;
  hotspots: ArchHotspot[];
};

/** Pre-rendered with beautiful-mermaid (scripts/render-mermaid.mjs). Do not import the package here. */
const ARCH_DIAGRAMS: ArchDiagram[] = [
  {
    id: "overview",
    title: "Overview",
    kind: "flowchart",
    svg:
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 80" width="100%" height="auto" style="--bg:#1e1e1e;--fg:#d4d4d4;--accent:#3794ff">' +
      '<style>text { font-family: system-ui, sans-serif; }</style>' +
      '<g class="node" data-id="entry" data-label="Entry point">' +
      '<rect x="20" y="20" width="160" height="40" rx="4" fill="color-mix(in srgb, var(--fg,#d4d4d4) 3%, var(--bg,#1e1e1e))" stroke="color-mix(in srgb, var(--fg,#d4d4d4) 20%, var(--bg,#1e1e1e))" stroke-width="1" />' +
      '<text x="100" y="45" text-anchor="middle" font-size="13" fill="var(--fg,#d4d4d4)">Entry point</text>' +
      "</g></svg>",
    hotspots: [{ label: "Entry point", nodeId: "entry" }],
  },
];

type LaidOutNode = {
  id: string;
  x: number;
  y: number;
  row: number;
  col: number;
  rtl: boolean;
};

type LaidOutEdge = {
  key: string;
  from: string;
  to: string;
  sourceX: number;
  sourceY: number;
  targetX: number;
  targetY: number;
  kind: "along" | "wrap";
  label: string;
  labelX: number;
  labelY: number;
};

/** Agent must set to the target repo root (absolute path). */
const ROOT = "/REPLACE_WITH_REPO_ROOT";

// <map:file-map>
/** Global code-link registry — single source of truth. Sync reads ONLY this. */
const FILE_MAP = {
  // Replace this demo entry with real keys: "rel/path:Symbol" → { path, line, endLine?, label? }
  "src/example.ts:main": {
    path: `${ROOT}/src/example.ts`,
    line: 1,
    endLine: 5,
    label: "main",
  },
} as const satisfies Record<string, FileRef>;

type FileMapKey = keyof typeof FILE_MAP;

function fileRef(key: FileMapKey | string): FileRef {
  return FILE_MAP[key as FileMapKey];
}

/** Slice FILE_CONTENTS by FILE_MAP line range for sidebar DiffView. */
function snippet(key: FileMapKey | string): string {
  const ref = fileRef(key);
  const body = FILE_CONTENTS[ref.path];
  if (!body) return "";
  if (ref.line == null) return body.replace(/\n$/, "");
  const lines = body.replace(/\n$/, "").split("\n");
  const start = ref.line;
  const end = ref.endLine ?? ref.line;
  return lines.slice(start - 1, end).join("\n");
}
// </map:file-map>

// <map:file-contents>
/** Full file bodies for preview popups. Generated — do not edit. */
/** @generated by scripts/sync-file-map.ts (bun update.ts) */
const FILE_CONTENTS: Record<string, string> = {};
// </map:file-contents>

// <map:map-paths>
/** Unique abs paths for the file tree. Generated — do not edit. */
/** @generated by scripts/sync-file-map.ts (bun update.ts) */
const MAP_PATHS: string[] = [];
// </map:map-paths>

const NODE_W = 240;
const NODE_H = 96;
const GAP_X = 100;
const GAP_Y = 110;
const PAD = 40;
const COLS = 3;
const MIN_ZOOM = 0.55;
const MAX_ZOOM = 1.55;
const MIN_VIEWPORT_H = 360;
const MAX_VIEWPORT_H = 1400;
const DEFAULT_VIEWPORT_H = 580;
const MIN_ARCH_H = 220;
const MAX_ARCH_H = 900;
const DEFAULT_ARCH_H = 360;
const MIN_ARCH_ZOOM = 0.4;
const MAX_ARCH_ZOOM = 2.5;
const MIN_SIDEBAR_W = 240;
const MAX_SIDEBAR_W = 900;
const DEFAULT_SIDEBAR_W = 320;
const MIN_TREE_W = 200;
const MAX_TREE_W = 720;
const DEFAULT_TREE_W = 280;

const NODES: MapNode[] = [
  {
    id: "entry",
    label: "Entry point",
    teaser: "Where the flow starts",
    body: [
      {
        type: "prose",
        text: "Replace with your subsystem walkthrough. Interleave short prose with `{ type: \"code\", ref }` blocks keyed into FILE_MAP.",
      },
      {
        type: "code",
        ref: "src/example.ts:main",
        caption: "Example excerpt — run sync-file-map after adding real paths",
      },
    ],
    files: [fileRef("src/example.ts:main")],
  },
  {
    id: "core",
    label: "Core logic",
    teaser: "Middle of the path",
    body: [
      {
        type: "prose",
        text: "Add FILE_MAP entries for every code block and Source footer link. Prose-only sidebars are an anti-pattern.",
      },
    ],
    files: [],
  },
  {
    id: "output",
    label: "Output",
    teaser: "Where it ends",
    body: [
      {
        type: "prose",
        text: "Third placeholder node — agents replace ids, labels, teasers, body, and files.",
      },
    ],
    files: [],
  },
];

const EDGES: MapEdge[] = [
  {
    from: "entry",
    to: "core",
    label: "calls",
    body: [
      {
        type: "prose",
        text: "Edge sidebars explain relationships. Add code refs via FILE_MAP keys.",
      },
    ],
    files: [],
  },
  {
    from: "core",
    to: "output",
    label: "yields",
    body: [
      {
        type: "prose",
        text: "Second placeholder edge — replace label and body for your dependency story.",
      },
    ],
    files: [],
  },
];

const PATH = NODES.map((n) => n.id);


function edgeKey(from: string, to: string) {
  return `${from}->${to}`;
}

function clamp(n: number, lo: number, hi: number) {
  return Math.max(lo, Math.min(hi, n));
}

function richInline(text: string): ReactNode[] {
  return text.split(/(`[^`]+`)/g).map((part, i) => {
    if (part.startsWith("`") && part.endsWith("`") && part.length > 1) {
      return <Code key={i}>{part.slice(1, -1)}</Code>;
    }
    return part;
  });
}

function refPathLabel(ref: FileRef): string {
  const short = ref.path.startsWith(`${ROOT}/`)
    ? ref.path.slice(ROOT.length + 1)
    : ref.path;
  if (ref.line == null) return short;
  const end = ref.endLine != null && ref.endLine !== ref.line ? ref.endLine : null;
  return end != null ? `${short}:${ref.line}-${end}` : `${short}:${ref.line}`;
}

function highlightRange(ref: FileRef): { start?: number; end?: number } {
  if (ref.line == null) return {};
  const start = ref.line;
  const end = ref.endLine != null && ref.endLine >= start ? ref.endLine : start;
  return { start, end };
}

function fileToPreviewLines(
  content: string,
  start?: number,
  end?: number,
): DiffLineData[] {
  const lines = content.replace(/\n$/, "").split("\n");
  return lines.map((lineContent, idx) => {
    const n = idx + 1;
    const focused =
      start != null && end != null && n >= start && n <= end;
    return {
      type: focused ? "added" : "unchanged",
      content: lineContent,
      lineNumber: n,
    };
  });
}

function OpenExternalIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden="true">
      <path
        d="M5 3.5h7.5V11M12.5 3.5L3.5 12.5"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function CodePreviewModal({
  file,
  theme,
  onClose,
  onOpenInIde,
}: {
  file: FileRef;
  theme: ReturnType<typeof useHostTheme>;
  onClose: () => void;
  onOpenInIde: (ref: FileRef) => void;
}) {
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const content = FILE_CONTENTS[file.path];
  const { start, end } = highlightRange(file);
  const lines = content
    ? fileToPreviewLines(content, start, end)
    : fileToPreviewLines(
        "// File contents were not embedded for this path.\n// Use the open-in-IDE control to view it in the editor.",
      );

  useEffect(() => {
    const el = scrollRef.current;
    if (!el || start == null) return;
    const lineH = 18;
    el.scrollTop = Math.max(0, (start - 1) * lineH - 72);
  }, [file.path, start]);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label={refPathLabel(file)}
      onClick={onClose}
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 1000,
        background: "color-mix(in srgb, transparent 45%, black)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 24,
      }}
    >
      <div
        onClick={(e: { stopPropagation(): void }) => e.stopPropagation()}
        style={{
          width: "min(920px, 100%)",
          maxHeight: "min(80vh, 900px)",
          display: "flex",
          flexDirection: "column",
          background: theme.bg.elevated,
          border: `1px solid ${theme.stroke.primary}`,
          borderRadius: 10,
          overflow: "hidden",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            padding: "10px 12px",
            borderBottom: `1px solid ${theme.stroke.secondary}`,
            background: theme.bg.chrome,
          }}
        >
          <Text
            weight="semibold"
            style={{
              flex: 1,
              fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
              fontSize: 12,
              color: theme.text.primary,
              overflow: "hidden",
              textOverflow: "ellipsis",
              whiteSpace: "nowrap",
            }}
          >
            {refPathLabel(file)}
          </Text>
          <IconButton
            title="Open in editor"
            onClick={() => onOpenInIde(file)}
          >
            <OpenExternalIcon />
          </IconButton>
          <Button variant="ghost" onClick={onClose}>
            Close
          </Button>
        </div>
        <div
          ref={scrollRef}
          style={{
            flex: 1,
            overflow: "auto",
            background: theme.bg.editor,
            minHeight: 240,
          }}
        >
          <DiffView
            path={file.path}
            lines={lines}
            showLineNumbers
            showAccentStrip
          />
        </div>
        {!content ? (
          <div
            style={{
              padding: "8px 12px",
              borderTop: `1px solid ${theme.stroke.secondary}`,
            }}
          >
            <Text size="small" tone="secondary">
              Contents not embedded — open in editor for the full file.
            </Text>
          </div>
        ) : null}
      </div>
    </div>
  );
}


function relPath(abs: string): string {
  return abs.startsWith(`${ROOT}/`) ? abs.slice(ROOT.length + 1) : abs;
}

function fileRefKey(ref: FileRef): string {
  return `${ref.path}:${ref.line ?? 0}`;
}

function collectFiles(entity: {
  files: FileRef[];
  body: DocBlock[];
}): FileRef[] {
  const seen = new Set<string>();
  const out: FileRef[] = [];
  for (const f of entity.files) {
    const k = fileRefKey(f);
    if (!seen.has(k)) {
      seen.add(k);
      out.push(f);
    }
  }
  for (const b of entity.body) {
    if (b.type === "code") {
      const f = fileRef(b.ref);
      const k = fileRefKey(f);
      if (!seen.has(k)) {
        seen.add(k);
        out.push(f);
      }
    }
  }
  return out;
}

type TreeFile = {
  kind: "file";
  name: string;
  relPath: string;
  absPath: string;
};

type TreeDir = {
  kind: "dir";
  name: string;
  children: Map<string, TreeFile | TreeDir>;
};

function buildTree(absPaths: string[]): TreeDir {
  const root: TreeDir = { kind: "dir", name: "", children: new Map() };
  for (const abs of absPaths) {
    const rel = relPath(abs);
    const segments = rel.split("/");
    let current = root;
    for (let i = 0; i < segments.length; i++) {
      const seg = segments[i];
      const isFile = i === segments.length - 1;
      if (isFile) {
        current.children.set(seg, {
          kind: "file",
          name: seg,
          relPath: rel,
          absPath: abs,
        });
      } else {
        let child = current.children.get(seg);
        if (!child || child.kind === "file") {
          child = { kind: "dir", name: seg, children: new Map() };
          current.children.set(seg, child);
        }
        current = child;
      }
    }
  }
  return root;
}

/** File tree paths — prefer generated MAP_PATHS (from `bun update.ts`). */
function collectAllMapPaths(): string[] {
  if (MAP_PATHS.length > 0) return [...MAP_PATHS];
  // Fallback before first update: derive from FILE_MAP directly.
  return [
    ...new Set(Object.values(FILE_MAP).map((r) => r.path)),
  ].sort((a, b) => a.localeCompare(b));
}

function countFiles(dir: TreeDir): number {
  let n = 0;
  for (const child of dir.children.values()) {
    if (child.kind === "file") n++;
    else n += countFiles(child);
  }
  return n;
}

function dirShouldExpand(dirRelPath: string, hoverPaths: string[]): boolean {
  return hoverPaths.some(
    (p) => p === dirRelPath || p.startsWith(`${dirRelPath}/`),
  );
}

function leavePreview(
  e: {
    relatedTarget: EventTarget | null;
    currentTarget: EventTarget & { contains(node: Node): boolean };
  },
  onClearPreview: () => void,
) {
  const next = e.relatedTarget;
  if (next instanceof Node && e.currentTarget.contains(next)) return;
  onClearPreview();
}

function sidebarType(width: number) {
  const t = clamp((width - MIN_SIDEBAR_W) / (MAX_SIDEBAR_W - MIN_SIDEBAR_W), 0, 1);
  return {
    title: 14 + t * 6,
    body: 12 + t * 4,
    meta: 11 + t * 3,
    code: 11 + t * 3,
    gap: 10 + t * 6,
    pad: 12 + t * 8,
  };
}

function codeToDiffLines(code: string, startLine?: number): DiffLineData[] {
  const lines = code.replace(/\n$/, "").split("\n");
  return lines.map((content, idx) => ({
    type: "unchanged" as const,
    content,
    ...(startLine != null ? { lineNumber: startLine + idx } : {}),
  }));
}

function renderDocBlocks(
  blocks: DocBlock[],
  typeScale: ReturnType<typeof sidebarType>,
  theme: ReturnType<typeof useHostTheme>,
  previewFile: (ref: FileRef) => void,
  onPreviewFiles?: (refs: FileRef[]) => void,
  onClearPreview?: () => void,
): ReactNode {
  return (
    <Stack gap={typeScale.gap}>
      {blocks.map((block, i) => {
        switch (block.type) {
          case "prose":
            return (
              <Text
                key={i}
                style={{
                  fontSize: typeScale.body,
                  lineHeight: 1.45,
                  color: theme.text.secondary,
                }}
              >
                {richInline(block.text)}
              </Text>
            );
          case "code": {
            const key = block.ref;
            const file = fileRef(key);
            const code = snippet(key);
            return (
              <div
                key={i}
                onMouseEnter={() => onPreviewFiles?.([file])}
                onMouseLeave={(e: {
                  currentTarget: EventTarget & { contains(n: Node): boolean };
                  relatedTarget: EventTarget | null;
                }) => {
                  if (onClearPreview) leavePreview(e, onClearPreview);
                }}
              >
                <Stack gap={4}>
                  <Button
                    variant="ghost"
                    onClick={() => previewFile(file)}
                    style={{
                      justifyContent: "flex-start",
                      height: "auto",
                      minHeight: 0,
                      padding: "2px 4px",
                    }}
                  >
                    <Text
                      style={{
                        fontFamily:
                          "ui-monospace, SFMono-Regular, Menlo, monospace",
                        color: theme.text.link,
                        fontSize: typeScale.code,
                        textAlign: "left",
                      }}
                    >
                      {refPathLabel(file)}
                    </Text>
                  </Button>
                  {block.caption ? (
                    <Text
                      style={{
                        fontSize: typeScale.meta,
                        color: theme.text.tertiary,
                        lineHeight: 1.35,
                      }}
                    >
                      {block.caption}
                    </Text>
                  ) : null}
                  <div
                    role="button"
                    tabIndex={0}
                    title="Preview full file"
                    onClick={() => previewFile(file)}
                    onKeyDown={(e: { key: string; preventDefault(): void }) => {
                      if (e.key === "Enter" || e.key === " ") {
                        e.preventDefault();
                        previewFile(file);
                      }
                    }}
                    style={{
                      border: `1px solid ${theme.stroke.secondary}`,
                      borderRadius: 6,
                      overflow: "hidden",
                      backgroundColor: theme.bg.editor,
                      cursor: "pointer",
                    }}
                  >
                    <DiffView
                      path={file.path}
                      lines={codeToDiffLines(code, file.line)}
                      showLineNumbers={file.line != null}
                      showAccentStrip={false}
                    />
                  </div>
                </Stack>
              </div>
            );
          }
          default: {
            const _exhaustive: never = block;
            return _exhaustive;
          }
        }
      })}
    </Stack>
  );
}

function layoutWrappedPath(pathIds: string[]): {
  nodes: LaidOutNode[];
  width: number;
  height: number;
} {
  const nodes = pathIds.map((id, i) => {
    const row = Math.floor(i / COLS);
    const iInRow = i % COLS;
    const rtl = row % 2 === 1;
    const col = rtl ? COLS - 1 - iInRow : iInRow;
    return {
      id,
      x: PAD + col * (NODE_W + GAP_X),
      y: PAD + row * (NODE_H + GAP_Y),
      row,
      col,
      rtl,
    };
  });
  const rows = Math.ceil(pathIds.length / COLS);
  const width = PAD * 2 + COLS * NODE_W + (COLS - 1) * GAP_X;
  const height =
    PAD * 2 + rows * NODE_H + Math.max(0, rows - 1) * GAP_Y;
  return { nodes, width, height };
}

function sideAnchor(
  n: LaidOutNode,
  side: "left" | "right" | "top" | "bottom",
): { x: number; y: number } {
  const cx = n.x + NODE_W / 2;
  const cy = n.y + NODE_H / 2;
  if (side === "left") return { x: n.x, y: cy };
  if (side === "right") return { x: n.x + NODE_W, y: cy };
  if (side === "top") return { x: cx, y: n.y };
  return { x: cx, y: n.y + NODE_H };
}

function buildPathEdges(
  laidOut: LaidOutNode[],
  edgeMeta: Map<string, MapEdge>,
): LaidOutEdge[] {
  const edges: LaidOutEdge[] = [];
  for (let i = 0; i < laidOut.length - 1; i++) {
    const from = laidOut[i];
    const to = laidOut[i + 1];
    const key = edgeKey(from.id, to.id);
    const meta = edgeMeta.get(key);
    const wrap = from.row !== to.row;
    if (wrap) {
      const s = sideAnchor(from, "bottom");
      const t = sideAnchor(to, "top");
      const midY = (s.y + t.y) / 2;
      edges.push({
        key,
        from: from.id,
        to: to.id,
        sourceX: s.x,
        sourceY: s.y,
        targetX: t.x,
        targetY: t.y,
        kind: "wrap",
        label: meta?.label ?? "",
        labelX: s.x + 18,
        labelY: midY,
      });
    } else {
      const forward = !from.rtl;
      const s = sideAnchor(from, forward ? "right" : "left");
      const t = sideAnchor(to, forward ? "left" : "right");
      const midX = (s.x + t.x) / 2;
      const midY = (s.y + t.y) / 2;
      edges.push({
        key,
        from: from.id,
        to: to.id,
        sourceX: s.x,
        sourceY: s.y,
        targetX: t.x,
        targetY: t.y,
        kind: "along",
        label: meta?.label ?? "",
        labelX: midX,
        labelY: midY - 22,
      });
    }
  }
  return edges;
}

function edgePath(e: LaidOutEdge): string {
  if (e.kind === "wrap") {
    const midY = (e.sourceY + e.targetY) / 2;
    return `M ${e.sourceX} ${e.sourceY} L ${e.sourceX} ${midY} L ${e.targetX} ${midY} L ${e.targetX} ${e.targetY}`;
  }
  const mx = (e.sourceX + e.targetX) / 2;
  return `M ${e.sourceX} ${e.sourceY} C ${mx} ${e.sourceY}, ${mx} ${e.targetY}, ${e.targetX} ${e.targetY}`;
}

function renderTreeDir(
  dir: TreeDir,
  dirRelPath: string,
  depth: number,
  selectedPaths: string[],
  hoverPaths: string[],
  theme: ReturnType<typeof useHostTheme>,
  previewFile: (ref: FileRef) => void,
): ReactNode {
  const activePaths = [...new Set([...selectedPaths, ...hoverPaths])];
  const entries = [...dir.children.entries()].sort((a, b) => {
    const aDir = a[1].kind === "dir";
    const bDir = b[1].kind === "dir";
    if (aDir !== bDir) return aDir ? -1 : 1;
    return a[0].localeCompare(b[0]);
  });

  return entries.map(([name, entry]) => {
    if (entry.kind === "dir") {
      const childDirPath = dirRelPath ? `${dirRelPath}/${name}` : name;
      const expanded =
        activePaths.length > 0 && dirShouldExpand(childDirPath, activePaths);
      const fileCount = countFiles(entry);
      const indent = depth * 14;

      return (
        <div key={childDirPath}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 4,
              padding: "2px 6px 2px 0",
              paddingLeft: indent + 6,
              borderRadius: 4,
              background: expanded ? theme.fill.tertiary : "transparent",
              borderLeft: expanded
                ? `2px solid ${theme.stroke.primary}`
                : "2px solid transparent",
            }}
          >
            <Text
              size="small"
              style={{
                fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
                fontSize: 11,
                color: theme.text.secondary,
                flex: 1,
                overflow: "hidden",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
              }}
            >
              {expanded ? "▾" : "▸"} {name}
            </Text>
            {!expanded && activePaths.length === 0 ? (
              <Text
                size="small"
                style={{ fontSize: 10, color: theme.text.quaternary }}
              >
                {fileCount}
              </Text>
            ) : null}
          </div>
          {expanded
            ? renderTreeDir(
                entry,
                childDirPath,
                depth + 1,
                selectedPaths,
                hoverPaths,
                theme,
                previewFile,
              )
            : null}
        </div>
      );
    }

    const isSelected = selectedPaths.includes(entry.relPath);
    const isHovered = hoverPaths.includes(entry.relPath);
    const highlighted = isSelected || isHovered;
    const indent = depth * 14;

    return (
      <div
        key={entry.relPath}
        role="button"
        tabIndex={0}
        onClick={() => previewFile({ path: entry.absPath })}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            previewFile({ path: entry.absPath });
          }
        }}
        style={{
          display: "flex",
          alignItems: "center",
          padding: "2px 6px 2px 0",
          paddingLeft: indent + 6,
          borderRadius: 4,
          cursor: "pointer",
          background: isSelected
            ? theme.fill.secondary
            : isHovered
              ? theme.fill.tertiary
              : "transparent",
          borderLeft: highlighted
            ? `2px solid ${theme.accent.primary}`
            : "2px solid transparent",
        }}
      >
        <Text
          size="small"
          style={{
            fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
            fontSize: 11,
            color: highlighted ? theme.accent.primary : theme.text.link,
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
            fontWeight: isSelected ? 600 : undefined,
          }}
        >
          {name}
        </Text>
      </div>
    );
  });
}

function BuiltinFileTreePanel({
  files,
  selectedPaths,
  hoverPaths,
  theme,
  height,
  width,
  previewFile,
}: {
  files: { relPath: string; absPath: string }[];
  selectedPaths: string[];
  hoverPaths: string[];
  theme: ReturnType<typeof useHostTheme>;
  height: number;
  width: number;
  previewFile: (ref: FileRef) => void;
}) {
  const tree = buildTree(files.map((f) => f.absPath));
  const totalFiles = countFiles(tree);

  return (
    <aside
      style={{
        width,
        flexShrink: 0,
        boxSizing: "border-box",
        height,
        overflow: "auto",
        borderRadius: "0 8px 8px 0",
        border: `1px solid ${theme.stroke.secondary}`,
        borderLeft: "none",
        background: theme.bg.elevated,
        display: "flex",
        flexDirection: "column",
        gap: 8,
        padding: "12px 10px",
      }}
    >
      <Stack gap={2}>
        <Text weight="semibold" size="small">
          Files in this map
        </Text>
        <Text size="small" tone="tertiary" style={{ fontSize: 10 }}>
          {totalFiles} file{totalFiles === 1 ? "" : "s"} · selection sticks ·
          hover adds more · drag left edge to resize
        </Text>
      </Stack>
      <div style={{ flex: 1, minHeight: 0 }}>
        {renderTreeDir(
          tree,
          "",
          0,
          selectedPaths,
          hoverPaths,
          theme,
          previewFile,
        )}
      </div>
    </aside>
  );
}

function FileTreePanel(props: {
  files: { relPath: string; absPath: string }[];
  selectedPaths: string[];
  hoverPaths: string[];
  theme: ReturnType<typeof useHostTheme>;
  height: number;
  width: number;
  previewFile: (ref: FileRef) => void;
}) {
  const HostTree = (MapHost as { FileTreePanel?: typeof BuiltinFileTreePanel })
    .FileTreePanel;
  if (HostTree) return <HostTree {...props} />;
  return <BuiltinFileTreePanel {...props} />;
}

function resolveHotspotEntity(h: ArchHotspot): { files: FileRef[]; body: DocBlock[] } | null {
  if (h.nodeId) {
    const n = NODES.find((x) => x.id === h.nodeId);
    return n ?? null;
  }
  if (h.edgeKey) {
    const e = EDGES.find((x) => edgeKey(x.from, x.to) === h.edgeKey);
    return e ?? null;
  }
  return null;
}

/** Intrinsic SVG size from viewBox — needed so pan/zoom isn't fighting width=100%. */
function svgWorldSize(svg: string): { w: number; h: number } {
  const m = svg.match(/viewBox="([^"]+)"/);
  if (!m) return { w: 800, h: 600 };
  const parts = m[1].trim().split(/[\s,]+/).map(Number);
  const w = parts[2];
  const h = parts[3];
  if (!Number.isFinite(w) || !Number.isFinite(h) || w <= 0 || h <= 0) {
    return { w: 800, h: 600 };
  }
  return { w, h };
}

function svgForCamera(svg: string, w: number, h: number): string {
  return svg
    .replace(/\swidth="[^"]*"/, ` width="${w}"`)
    .replace(/\sheight="[^"]*"/, ` height="${h}"`);
}

function cssEscapeAttr(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Pointer cursor on hotspot shapes + accent stroke on the focused hotspot. */
function svgWithHotspotChrome(
  svg: string,
  hotspots: ArchHotspot[],
  activeLabels: string[],
  accent: string,
): string {
  const pointerSel = hotspots
    .map((h) => `[data-label="${cssEscapeAttr(h.label)}"]`)
    .join(", ");
  const activeGroupSel = activeLabels
    .map((l) => `[data-label="${cssEscapeAttr(l)}"]`)
    .join(", ");
  const activeRectSel = activeLabels
    .map((l) => `[data-label="${cssEscapeAttr(l)}"] > rect`)
    .join(", ");

  const rules: string[] = [];
  if (pointerSel) {
    rules.push(`${pointerSel}, ${pointerSel} * { cursor: pointer; }`);
  }
  if (activeRectSel) {
    rules.push(
      `${activeRectSel} { stroke: ${accent} !important; stroke-width: 2.5 !important; }`,
    );
  }
  if (activeGroupSel) {
    rules.push(
      `${activeGroupSel} > rect:first-of-type { fill: color-mix(in srgb, ${accent} 18%, var(--_node-fill, transparent)) !important; }`,
    );
  }
  if (rules.length === 0) return svg;

  const style = `<style data-arch-hotspot-chrome>${rules.join("\n")}</style>`;
  return svg.replace(/<svg([^>]*)>/, `<svg$1>${style}`);
}

function ArchitecturePanel({
  theme,
  focus,
  onSelectNode,
  onSelectEdge,
  onPreviewFiles,
  onClearPreview,
}: {
  theme: ReturnType<typeof useHostTheme>;
  focus: Focus;
  onSelectNode: (id: string) => void;
  onSelectEdge: (key: string) => void;
  onPreviewFiles: (refs: FileRef[]) => void;
  onClearPreview: () => void;
}) {
  const [activeId, setActiveId] = useCanvasState(
    "archDiagram",
    ARCH_DIAGRAMS[0].id,
  );
  const [archView, setArchView] = useCanvasState<View>("archView", {
    x: 16,
    y: 16,
    zoom: 1,
  });
  const [archH, setArchH] = useCanvasState("archViewportH", DEFAULT_ARCH_H);
  const [dragging, setDragging] = useState(false);
  const [overHotspot, setOverHotspot] = useState(false);
  const dragOriginRef = useRef<{
    px: number;
    py: number;
    vx: number;
    vy: number;
  } | null>(null);
  const didPanRef = useRef(false);
  /** Saved on pointerdown — capture retargets pointerup to the viewport. */
  const downTargetRef = useRef<Element | null>(null);
  const [resizingH, setResizingH] = useState(false);
  const resizeHRef = useRef<{ py: number; height: number } | null>(null);

  const diagram =
    ARCH_DIAGRAMS.find((d) => d.id === activeId) ?? ARCH_DIAGRAMS[0];
  const world = svgWorldSize(diagram.svg);

  const activeLabels = useMemo(
    () =>
      diagram.hotspots
        .filter((h) => {
          if (h.nodeId && focus.kind === "node") return focus.id === h.nodeId;
          if (h.edgeKey && focus.kind === "edge") return focus.key === h.edgeKey;
          return false;
        })
        .map((h) => h.label),
    [diagram.hotspots, focus],
  );

  const cameraSvg = useMemo(
    () =>
      svgWithHotspotChrome(
        svgForCamera(diagram.svg, world.w, world.h),
        diagram.hotspots,
        activeLabels,
        theme.accent.primary,
      ),
    [diagram.svg, diagram.hotspots, world.w, world.h, activeLabels, theme.accent.primary],
  );

  function activate(h: ArchHotspot) {
    if (h.nodeId) onSelectNode(h.nodeId);
    else if (h.edgeKey) onSelectEdge(h.edgeKey);
  }

  function hotspotActive(h: ArchHotspot): boolean {
    if (h.nodeId && focus.kind === "node") return focus.id === h.nodeId;
    if (h.edgeKey && focus.kind === "edge") return focus.key === h.edgeKey;
    return false;
  }

  function setArchZoom(next: number) {
    setArchView((v) => ({
      ...v,
      zoom: clamp(next, MIN_ARCH_ZOOM, MAX_ARCH_ZOOM),
    }));
  }

  function fitArch() {
    setArchView({ x: 16, y: 16, zoom: 1 });
  }

  function hitFromEvent(target: Element): ArchHotspot | null {
    const labeled = target.closest(
      "[data-label], .node, .actor, .class-node",
    );
    const fromAttr = labeled?.getAttribute("data-label")?.trim();
    const fromText = target.closest("text, tspan")?.textContent?.trim();
    const label = fromAttr || fromText;
    if (!label) return null;
    return (
      diagram.hotspots.find(
        (h) => label === h.label || label.includes(h.label),
      ) ?? null
    );
  }

  function updateHoverCursor(clientX: number, clientY: number) {
    if (dragOriginRef.current) {
      setOverHotspot(false);
      return;
    }
    const under = document.elementFromPoint(clientX, clientY);
    setOverHotspot(!!(under && hitFromEvent(under)));
  }

  return (
    <Stack gap={10}>
      <Stack gap={4}>
        <Text weight="semibold">Architecture</Text>
        <Text size="small" tone="secondary">
          Pan · scroll to zoom · drag the bottom edge to resize · click a shape
          or chip to focus the map sidebar.
        </Text>
      </Stack>
      <Row gap={6} wrap align="center">
        {ARCH_DIAGRAMS.map((d) => (
          <Button
            key={d.id}
            variant={d.id === diagram.id ? "primary" : "secondary"}
            onClick={() => {
              setActiveId(d.id);
              fitArch();
            }}
          >
            {`${d.title} · ${d.kind}`}
          </Button>
        ))}
        <Text size="small" tone="quaternary">
          |
        </Text>
        <Button
          variant="secondary"
          onClick={() => setArchZoom(archView.zoom - 0.15)}
        >
          Zoom −
        </Button>
        <Button
          variant="secondary"
          onClick={() => setArchZoom(archView.zoom + 0.15)}
        >
          Zoom +
        </Button>
        <Button variant="secondary" onClick={fitArch}>
          Fit
        </Button>
        <Text size="small" tone="tertiary">
          {Math.round(archView.zoom * 100)}%
        </Text>
      </Row>

      <div>
        <div
          data-arch-viewport
          style={{
            position: "relative",
            width: "100%",
            height: archH,
            overflow: "hidden",
            borderRadius: "8px 8px 0 0",
            border: `1px solid ${theme.stroke.secondary}`,
            backgroundColor: theme.bg.editor,
            backgroundImage: `radial-gradient(${theme.stroke.tertiary} 1px, transparent 1px)`,
            backgroundSize: "18px 18px",
            cursor: dragging
              ? "grabbing"
              : overHotspot
                ? "pointer"
                : "grab",
            userSelect: "none",
          }}
          onPointerDown={(e) => {
            if ((e.target as HTMLElement).closest("[data-arch-resize]")) return;
            didPanRef.current = false;
            downTargetRef.current = e.target as Element;
            dragOriginRef.current = {
              px: e.clientX,
              py: e.clientY,
              vx: archView.x,
              vy: archView.y,
            };
            setOverHotspot(false);
            setDragging(true);
            (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
          }}
          onPointerMove={(e) => {
            const origin = dragOriginRef.current;
            if (!origin) {
              updateHoverCursor(e.clientX, e.clientY);
              return;
            }
            const dx = e.clientX - origin.px;
            const dy = e.clientY - origin.py;
            if (Math.abs(dx) > 3 || Math.abs(dy) > 3) didPanRef.current = true;
            setArchView({
              ...archView,
              x: origin.vx + dx,
              y: origin.vy + dy,
            });
          }}
          onPointerUp={(e) => {
            try {
              (e.currentTarget as HTMLElement).releasePointerCapture(
                e.pointerId,
              );
            } catch {
              /* already released */
            }
            if (!didPanRef.current) {
              // Capture retargets e.target to the viewport; prefer geometry hit,
              // then the original down target.
              const under = document.elementFromPoint(e.clientX, e.clientY);
              const hit =
                (under ? hitFromEvent(under) : null) ??
                (downTargetRef.current
                  ? hitFromEvent(downTargetRef.current)
                  : null);
              if (hit) activate(hit);
            }
            dragOriginRef.current = null;
            downTargetRef.current = null;
            didPanRef.current = false;
            setDragging(false);
            updateHoverCursor(e.clientX, e.clientY);
          }}
          onPointerLeave={() => setOverHotspot(false)}
          onWheel={(e) => {
            const delta = e.deltaY > 0 ? -0.08 : 0.08;
            setArchZoom(archView.zoom + delta);
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              top: 0,
              width: world.w,
              height: world.h,
              transform: `translate(${archView.x}px, ${archView.y}px) scale(${archView.zoom})`,
              transformOrigin: "0 0",
              padding: 8,
              boxSizing: "content-box",
            }}
            dangerouslySetInnerHTML={{ __html: cameraSvg }}
          />
        </div>
        <div
          data-arch-resize
          title="Drag to resize architecture height"
          onPointerDown={(e) => {
            e.preventDefault();
            e.stopPropagation();
            (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
            setResizingH(true);
            resizeHRef.current = { py: e.clientY, height: archH };
          }}
          onPointerMove={(e) => {
            const origin = resizeHRef.current;
            if (!origin) return;
            setArchH(
              clamp(
                origin.height + (e.clientY - origin.py),
                MIN_ARCH_H,
                MAX_ARCH_H,
              ),
            );
          }}
          onPointerUp={(e) => {
            (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId);
            setResizingH(false);
            resizeHRef.current = null;
          }}
          style={{
            height: 12,
            marginTop: -1,
            cursor: "ns-resize",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            borderRadius: "0 0 8px 8px",
            background: resizingH
              ? theme.fill.secondary
              : theme.fill.tertiary,
            border: `1px solid ${theme.stroke.secondary}`,
            borderTop: "none",
          }}
        >
          <div
            style={{
              width: 40,
              height: 3,
              borderRadius: 2,
              background: theme.stroke.primary,
            }}
          />
        </div>
      </div>

      <Row gap={6} wrap>
        {diagram.hotspots.map((h) => {
          const active = hotspotActive(h);
          return (
            <div
              key={`${h.label}:${h.nodeId ?? h.edgeKey ?? ""}`}
              onMouseEnter={() => {
                const ent = resolveHotspotEntity(h);
                if (ent) onPreviewFiles(collectFiles(ent));
              }}
              onMouseLeave={onClearPreview}
            >
              <Button
                variant={active ? "primary" : "secondary"}
                onClick={() => activate(h)}
              >
                {h.label}
              </Button>
            </div>
          );
        })}
      </Row>
    </Stack>
  );
}
export default function MapView() {
  const theme = useHostTheme();
  const dispatch = useCanvasAction();
  const [focus, setFocus] = useCanvasState<Focus>("focus", {
    kind: "node",
    id: PATH[0],
  });
  const [view, setView] = useCanvasState<View>("view", {
    x: 16,
    y: 16,
    zoom: 1,
  });
  const [viewportH, setViewportH] = useCanvasState(
    "viewportH",
    DEFAULT_VIEWPORT_H,
  );
  const [sidebarW, setSidebarW] = useCanvasState(
    "sidebarW",
    DEFAULT_SIDEBAR_W,
  );
  const [sidebarOpen, setSidebarOpen] = useCanvasState("sidebarOpen", true);
  const [treeW, setTreeW] = useCanvasState("treeW", DEFAULT_TREE_W);
  const [dragging, setDragging] = useState(false);
  const [dragOrigin, setDragOrigin] = useState<{
    px: number;
    py: number;
    vx: number;
    vy: number;
  } | null>(null);
  const [resizingH, setResizingH] = useState(false);
  const resizeHRef = useRef<{ py: number; height: number } | null>(null);
  const [resizingW, setResizingW] = useState(false);
  const resizeWRef = useRef<{ px: number; width: number } | null>(null);
  const [resizingTreeW, setResizingTreeW] = useState(false);
  const resizeTreeWRef = useRef<{ px: number; width: number } | null>(null);
  const [hoverPaths, setHoverPaths] = useState<string[]>([]);
  const [filePreview, setFilePreview] = useState<FileRef | null>(null);

  const mapFiles = useMemo(
    () =>
      collectAllMapPaths().map((absPath) => ({
        absPath,
        relPath: relPath(absPath),
      })),
    [],
  );

  function previewFiles(refs: FileRef[]) {
    setHoverPaths([
      ...new Set(refs.map((r) => relPath(r.path))),
    ]);
  }

  function clearPreview() {
    setHoverPaths([]);
  }

  function previewFile(ref: FileRef) {
    setFilePreview(ref);
  }

  const edgeMeta = new Map(
    EDGES.map((e) => [edgeKey(e.from, e.to), e] as const),
  );
  const layout = layoutWrappedPath(PATH);
  const nodeById = new Map(layout.nodes.map((n) => [n.id, n]));
  const laidEdges = buildPathEdges(layout.nodes, edgeMeta);

  const selectedNode =
    focus.kind === "node"
      ? (NODES.find((n) => n.id === focus.id) ?? NODES[0])
      : null;
  const selectedEdge =
    focus.kind === "edge" ? (edgeMeta.get(focus.key) ?? null) : null;
  const selectedEntity =
    selectedEdge ?? selectedNode ?? NODES[0];
  const selectedPaths = [
    ...new Set(collectFiles(selectedEntity).map((f) => relPath(f.path))),
  ];
  const pathIndex = selectedNode ? PATH.indexOf(selectedNode.id) : -1;
  const typeScale = sidebarType(sidebarW);

  function selectNode(id: string) {
    setFocus({ kind: "node", id });
    setSidebarOpen(true);
  }

  function selectEdge(key: string) {
    setFocus({ kind: "edge", key });
    setSidebarOpen(true);
  }

  function openInIde(ref: FileRef) {
    const { start, end } = highlightRange(ref);
    dispatch({
      type: "openFile",
      path: ref.path,
      ...(start != null
        ? {
            selection: {
              startLineNumber: start,
              startColumn: 1,
              endLineNumber: end ?? start,
              endColumn: 1,
            },
          }
        : {}),
    });
  }

  function go(delta: number) {
    const base =
      focus.kind === "node" ? PATH.indexOf(focus.id) : Math.max(0, pathIndex);
    const next = PATH[base + delta];
    if (next) selectNode(next);
  }

  function setZoom(next: number) {
    setView((v) => ({ ...v, zoom: clamp(next, MIN_ZOOM, MAX_ZOOM) }));
  }

  function fit() {
    setView({ x: 16, y: 16, zoom: 1 });
  }

  const viewportStyle: CSSProperties = {
    position: "relative",
    width: "100%",
    height: viewportH,
    overflow: "hidden",
    border: `1px solid ${theme.stroke.secondary}`,
    borderRadius: 8,
    backgroundColor: theme.bg.editor,
    backgroundImage: `radial-gradient(${theme.stroke.tertiary} 1px, transparent 1px)`,
    backgroundSize: "18px 18px",
    cursor: dragging ? "grabbing" : "grab",
    userSelect: "none",
  };

  const worldStyle: CSSProperties = {
    position: "absolute",
    left: 0,
    top: 0,
    width: layout.width,
    height: layout.height,
    transform: `translate(${view.x}px, ${view.y}px) scale(${view.zoom})`,
    transformOrigin: "0 0",
  };

  const sidebarTitle =
    selectedEdge != null
      ? `${selectedEdge.label}: ${selectedEdge.from} → ${selectedEdge.to}`
      : (selectedNode?.label ?? "");
  const sidebarBody = selectedEdge?.body ?? selectedNode?.body ?? [];
  const sidebarFiles = selectedEdge?.files ?? selectedNode?.files ?? [];

  return (
    <Stack gap={16} style={{ padding: 20 }}>
      <Stack gap={6}>
        <H1>Map</H1>
        <Text tone="secondary">
          Interactive architecture diagram + snake flow map. Click a node or edge —
          the left sidebar shows prose, code excerpts, and source
          backlinks. Hover to preview files in the right tree.
        </Text>
      </Stack>

      <ArchitecturePanel
        theme={theme}
        focus={focus}
        onSelectNode={selectNode}
        onSelectEdge={selectEdge}
        onPreviewFiles={previewFiles}
        onClearPreview={clearPreview}
      />

      <Row gap={8} wrap align="center">
        <Button variant="secondary" onClick={() => setZoom(view.zoom - 0.15)}>
          Zoom −
        </Button>
        <Button variant="secondary" onClick={() => setZoom(view.zoom + 0.15)}>
          Zoom +
        </Button>
        <Button variant="secondary" onClick={fit}>
          Fit
        </Button>
        <Text size="small" tone="tertiary">
          {Math.round(view.zoom * 100)}%
        </Text>
        <Text size="small" tone="quaternary">
          |
        </Text>
        <Button
          variant="secondary"
          disabled={pathIndex <= 0 && focus.kind === "node"}
          onClick={() => go(-1)}
        >
          Prev
        </Button>
        <Pill>
          {focus.kind === "node"
            ? `${pathIndex + 1} / ${PATH.length}`
            : "edge"}
        </Pill>
        <Button
          variant="secondary"
          disabled={
            focus.kind === "node"
              ? pathIndex >= PATH.length - 1
              : false
          }
          onClick={() => go(1)}
        >
          Next
        </Button>
        {!sidebarOpen ? (
          <Button variant="secondary" onClick={() => setSidebarOpen(true)}>
            Open details
          </Button>
        ) : null}
        <Text size="small" tone="tertiary">
          Pan map · resize map height · resize sidebar · click nodes or edges ·
          hover to preview files
        </Text>
      </Row>

      <div
        style={{
          display: "flex",
          flexDirection: "row",
          alignItems: "stretch",
          width: "100%",
          gap: 0,
        }}
      >
        {sidebarOpen ? (
          <div
            style={{
              display: "flex",
              flexDirection: "row",
              flexShrink: 0,
              height: viewportH + 12,
            }}
          >
            <aside
              style={{
                width: sidebarW,
                boxSizing: "border-box",
                padding: typeScale.pad,
                overflow: "auto",
                borderRadius: "8px 0 0 8px",
                border: `1px solid ${theme.stroke.secondary}`,
                borderRight: "none",
                background: theme.bg.elevated,
                display: "flex",
                flexDirection: "column",
                gap: typeScale.gap,
              }}
            >
              <Row gap={8} align="center" justify="space-between">
                <Pill size="sm" active>
                  {focus.kind === "edge" ? "Dependency" : "Step"}
                </Pill>
                <Button variant="ghost" onClick={() => setSidebarOpen(false)}>
                  Close
                </Button>
              </Row>
              <Text
                weight="semibold"
                style={{ fontSize: typeScale.title, lineHeight: 1.3 }}
              >
                {sidebarTitle}
              </Text>
              {renderDocBlocks(
                sidebarBody,
                typeScale,
                theme,
                previewFile,
                previewFiles,
                clearPreview,
              )}
              <Stack gap={6}>
                <Text
                  weight="semibold"
                  style={{ fontSize: typeScale.meta }}
                >
                  Source
                </Text>
                <Stack gap={4}>
                  {sidebarFiles.map((f) => (
                    <div
                      key={`${f.path}:${f.line ?? 0}`}
                      onMouseEnter={() => previewFiles([f])}
                      onMouseLeave={(e) => leavePreview(e, clearPreview)}
                    >
                      <Button
                        variant="ghost"
                        onClick={() => previewFile(f)}
                        style={{
                          justifyContent: "flex-start",
                          height: "auto",
                          minHeight: 0,
                          padding: "4px 6px",
                        }}
                      >
                        <Text
                          style={{
                            fontFamily:
                              "ui-monospace, SFMono-Regular, Menlo, monospace",
                            color: theme.text.link,
                            fontSize: typeScale.code,
                            textAlign: "left",
                          }}
                        >
                          {f.label ?? f.path.split("/").pop()}
                          {f.line != null ? `:${f.line}` : ""}
                        </Text>
                      </Button>
                    </div>
                  ))}
                </Stack>
              </Stack>
              {focus.kind === "node" ? (
                <Row gap={8} style={{ marginTop: "auto" }}>
                  <Button
                    variant="secondary"
                    disabled={pathIndex <= 0}
                    onClick={() => go(-1)}
                  >
                    Prev
                  </Button>
                  <Button
                    variant="secondary"
                    disabled={pathIndex >= PATH.length - 1}
                    onClick={() => go(1)}
                  >
                    Next
                  </Button>
                </Row>
              ) : selectedEdge ? (
                <Row gap={8} style={{ marginTop: "auto" }} wrap>
                  <Button
                    variant="secondary"
                    onClick={() => selectNode(selectedEdge.from)}
                  >
                    ← {selectedEdge.from}
                  </Button>
                  <Button
                    variant="secondary"
                    onClick={() => selectNode(selectedEdge.to)}
                  >
                    {selectedEdge.to} →
                  </Button>
                </Row>
              ) : null}
            </aside>
            <div
              data-sidebar-resize
              title="Drag to resize sidebar"
              onPointerDown={(e) => {
                e.preventDefault();
                e.stopPropagation();
                (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
                setResizingW(true);
                resizeWRef.current = { px: e.clientX, width: sidebarW };
              }}
              onPointerMove={(e) => {
                const origin = resizeWRef.current;
                if (!origin) return;
                setSidebarW(
                  clamp(
                    origin.width + (e.clientX - origin.px),
                    MIN_SIDEBAR_W,
                    MAX_SIDEBAR_W,
                  ),
                );
              }}
              onPointerUp={(e) => {
                (e.currentTarget as HTMLElement).releasePointerCapture(
                  e.pointerId,
                );
                setResizingW(false);
                resizeWRef.current = null;
              }}
              style={{
                width: 8,
                cursor: "ew-resize",
                background: resizingW
                  ? theme.fill.secondary
                  : theme.fill.tertiary,
                border: `1px solid ${theme.stroke.secondary}`,
                borderLeft: "none",
                borderRadius: "0 8px 8px 0",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <div
                style={{
                  width: 2,
                  height: 28,
                  borderRadius: 1,
                  background: theme.stroke.primary,
                }}
              />
            </div>
          </div>
        ) : null}

        <div
          style={{
            position: "relative",
            flex: 1,
            minWidth: 0,
            marginLeft: sidebarOpen ? 8 : 0,
            display: "flex",
            flexDirection: "row",
            alignItems: "stretch",
          }}
        >
          <div style={{ flex: 1, minWidth: 0 }}>
          <div
            style={{
              ...viewportStyle,
              borderRadius: "8px 0 0 0",
            }}
            onPointerDown={(e) => {
              if ((e.target as HTMLElement).closest("[data-map-node]")) return;
              if ((e.target as HTMLElement).closest("[data-map-edge]")) return;
              if ((e.target as HTMLElement).closest("[data-resize-handle]"))
                return;
              if ((e.target as HTMLElement).closest("[data-tree-resize]"))
                return;
              setDragging(true);
              setDragOrigin({
                px: e.clientX,
                py: e.clientY,
                vx: view.x,
                vy: view.y,
              });
            }}
            onPointerMove={(e) => {
              if (!dragging || !dragOrigin) return;
              setView({
                ...view,
                x: dragOrigin.vx + (e.clientX - dragOrigin.px),
                y: dragOrigin.vy + (e.clientY - dragOrigin.py),
              });
            }}
            onPointerUp={() => {
              setDragging(false);
              setDragOrigin(null);
            }}
            onPointerLeave={() => {
              setDragging(false);
              setDragOrigin(null);
            }}
            onWheel={(e) => {
              const delta = e.deltaY > 0 ? -0.08 : 0.08;
              setZoom(view.zoom + delta);
            }}
          >
            <div style={worldStyle}>
              <svg
                width={layout.width}
                height={layout.height}
                style={{ position: "absolute", inset: 0, overflow: "visible" }}
              >
                <defs>
                  <marker
                    id="arrow"
                    markerWidth="8"
                    markerHeight="8"
                    refX="7"
                    refY="4"
                    orient="auto"
                  >
                    <path
                      d="M0,0 L8,4 L0,8 Z"
                      fill={theme.stroke.secondary}
                    />
                  </marker>
                  <marker
                    id="arrow-active"
                    markerWidth="8"
                    markerHeight="8"
                    refX="7"
                    refY="4"
                    orient="auto"
                  >
                    <path
                      d="M0,0 L8,4 L0,8 Z"
                      fill={theme.accent.primary}
                    />
                  </marker>
                </defs>
                {laidEdges.map((e) => {
                  const active =
                    focus.kind === "edge"
                      ? focus.key === e.key
                      : focus.kind === "node" &&
                        (e.from === focus.id || e.to === focus.id);
                  const d = edgePath(e);
                  return (
                    <g
                      key={e.key}
                      data-map-edge
                      onClick={(ev) => {
                        ev.stopPropagation();
                        selectEdge(e.key);
                      }}
                      onMouseEnter={() => {
                        const meta = edgeMeta.get(e.key);
                        if (meta) previewFiles(collectFiles(meta));
                      }}
                      onMouseLeave={clearPreview}
                      style={{ cursor: "pointer" }}
                    >
                      <path
                        d={d}
                        fill="none"
                        stroke="transparent"
                        strokeWidth={18}
                      />
                      <path
                        d={d}
                        fill="none"
                        stroke={
                          active
                            ? theme.accent.primary
                            : theme.stroke.secondary
                        }
                        strokeWidth={active ? 2.5 : 1.75}
                        markerEnd={
                          active ? "url(#arrow-active)" : "url(#arrow)"
                        }
                      />
                      {e.label ? (
                        <g>
                          <rect
                            x={e.labelX - Math.max(30, e.label.length * 3.6 + 10)}
                            y={e.labelY - 10}
                            width={Math.max(60, e.label.length * 7.2 + 20)}
                            height={18}
                            rx={4}
                            fill={theme.bg.editor}
                            stroke={
                              active
                                ? theme.accent.primary
                                : theme.stroke.tertiary
                            }
                            strokeWidth={1}
                          />
                          <text
                            x={e.labelX}
                            y={e.labelY + 3}
                            textAnchor="middle"
                            fill={
                              active
                                ? theme.accent.primary
                                : theme.text.secondary
                            }
                            fontSize={11}
                            fontFamily="ui-sans-serif, system-ui, sans-serif"
                          >
                            {e.label}
                          </text>
                        </g>
                      ) : null}
                    </g>
                  );
                })}
              </svg>

              {NODES.map((n, i) => {
                const pos = nodeById.get(n.id);
                if (!pos) return null;
                const isSelected =
                  focus.kind === "node" && focus.id === n.id;
                return (
                  <div
                    key={n.id}
                    data-map-node
                    onClick={() => selectNode(n.id)}
                    onMouseEnter={() => previewFiles(collectFiles(n))}
                    onMouseLeave={clearPreview}
                    style={{
                      position: "absolute",
                      left: pos.x,
                      top: pos.y,
                      width: NODE_W,
                      height: NODE_H,
                      boxSizing: "border-box",
                      padding: 12,
                      display: "flex",
                      flexDirection: "column",
                      gap: 8,
                      borderRadius: 8,
                      cursor: "pointer",
                      background: isSelected
                        ? theme.fill.tertiary
                        : theme.bg.elevated,
                      border: `1.5px solid ${
                        isSelected
                          ? theme.accent.primary
                          : theme.stroke.secondary
                      }`,
                    }}
                  >
                    <Row gap={8} align="center">
                      <Pill size="sm" active={isSelected}>
                        {i + 1}
                      </Pill>
                      <Text weight="semibold" size="small">
                        {n.label}
                      </Text>
                    </Row>
                    <Text
                      size="small"
                      tone="secondary"
                      style={{ lineHeight: "1.35" }}
                    >
                      {richInline(n.teaser)}
                    </Text>
                  </div>
                );
              })}
            </div>
          </div>
          <div
            data-resize-handle
            title="Drag to resize map height"
            onPointerDown={(e) => {
              e.preventDefault();
              e.stopPropagation();
              (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
              setResizingH(true);
              resizeHRef.current = { py: e.clientY, height: viewportH };
            }}
            onPointerMove={(e) => {
              const origin = resizeHRef.current;
              if (!origin) return;
              setViewportH(
                clamp(
                  origin.height + (e.clientY - origin.py),
                  MIN_VIEWPORT_H,
                  MAX_VIEWPORT_H,
                ),
              );
            }}
            onPointerUp={(e) => {
              (e.currentTarget as HTMLElement).releasePointerCapture(
                e.pointerId,
              );
              setResizingH(false);
              resizeHRef.current = null;
            }}
            style={{
              height: 12,
              marginTop: -1,
              cursor: "ns-resize",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              borderRadius: "0 0 0 8px",
              background: resizingH
                ? theme.fill.secondary
                : theme.fill.tertiary,
              border: `1px solid ${theme.stroke.secondary}`,
              borderTop: "none",
              borderRight: "none",
            }}
          >
            <div
              style={{
                width: 40,
                height: 3,
                borderRadius: 2,
                background: theme.stroke.primary,
              }}
            />
          </div>
          </div>
          <div
            style={{
              display: "flex",
              flexDirection: "row",
              flexShrink: 0,
              height: viewportH + 12,
            }}
          >
            <div
              data-tree-resize
              title="Drag to resize file tree"
              onPointerDown={(e) => {
                e.preventDefault();
                e.stopPropagation();
                (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
                setResizingTreeW(true);
                resizeTreeWRef.current = { px: e.clientX, width: treeW };
              }}
              onPointerMove={(e) => {
                const origin = resizeTreeWRef.current;
                if (!origin) return;
                setTreeW(
                  clamp(
                    origin.width - (e.clientX - origin.px),
                    MIN_TREE_W,
                    MAX_TREE_W,
                  ),
                );
              }}
              onPointerUp={(e) => {
                (e.currentTarget as HTMLElement).releasePointerCapture(
                  e.pointerId,
                );
                setResizingTreeW(false);
                resizeTreeWRef.current = null;
              }}
              style={{
                width: 8,
                cursor: "ew-resize",
                background: resizingTreeW
                  ? theme.fill.secondary
                  : theme.fill.tertiary,
                border: `1px solid ${theme.stroke.secondary}`,
                borderRight: "none",
                borderRadius: "8px 0 0 8px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <div
                style={{
                  width: 2,
                  height: 28,
                  borderRadius: 1,
                  background: theme.stroke.primary,
                }}
              />
            </div>
            <FileTreePanel
              files={mapFiles}
              selectedPaths={selectedPaths}
              hoverPaths={hoverPaths}
              theme={theme}
              height={viewportH + 12}
              width={treeW}
              previewFile={previewFile}
            />
          </div>
        </div>
      </div>

      {filePreview ? (
        <CodePreviewModal
          file={filePreview}
          theme={theme}
          onClose={() => setFilePreview(null)}
          onOpenInIde={openInIde}
        />
      ) : null}

      {/* Add more context below. */}
    </Stack>
  );
}
